// Skeletal animation for the procedural characters and creatures. Every
// model is built on a real Bone hierarchy with identity rest rotations, so a
// clip is just rotation offsets per bone name. Clips are generated by
// sampling a pose function over one cycle into quaternion keyframes and are
// played through three's AnimationMixer with cross-fades.

import {
  AnimationAction,
  AnimationClip,
  AnimationMixer,
  BufferAttribute,
  Euler,
  LoopOnce,
  LoopRepeat,
  Matrix4,
  Quaternion,
  QuaternionKeyframeTrack,
  Skeleton,
  SkinnedMesh,
  Vector3,
  VectorKeyframeTrack,
  type Bone,
  type BufferGeometry,
  type Material,
  type Object3D,
} from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import { prep } from './geometry';

export type Rot = [number, number, number];
export interface PoseFrame {
  rot: Record<string, Rot>;
  pos?: Record<string, Rot>;
}
export type PoseFn = (phase: number) => PoseFrame;

const e = new Euler();
const q = new Quaternion();

/**
 * Samples `fn` over one cycle. `bones` lists every bone the clip may touch,
 * so bones missing from a frame are keyed at rest (no pose leaks between
 * clips during cross-fades). `rest` supplies rest positions for pos tracks.
 */
export function makeClip(
  name: string,
  duration: number,
  fn: PoseFn,
  bones: readonly string[],
  rest: Record<string, Rot> = {},
  samples = 24,
  loop = true,
): AnimationClip {
  const n = loop ? samples + 1 : samples;
  const times = new Float32Array(n);
  const rotVals: Record<string, Float32Array> = {};
  const posVals: Record<string, Float32Array> = {};
  for (const b of bones) rotVals[b] = new Float32Array(n * 4);
  const frames: PoseFrame[] = [];
  for (let i = 0; i < n; i++) {
    const p = loop ? (i % samples) / samples : i / (samples - 1);
    times[i] = (loop ? i / samples : i / (samples - 1)) * duration;
    frames.push(fn(p));
  }
  for (const f of frames) for (const k of Object.keys(f.pos ?? {})) if (!posVals[k]) posVals[k] = new Float32Array(n * 3);
  frames.forEach((f, i) => {
    for (const b of bones) {
      const r = f.rot[b];
      if (r) q.setFromEuler(e.set(r[0], r[1], r[2], 'YXZ'));
      else q.identity();
      q.toArray(rotVals[b], i * 4);
    }
    for (const k of Object.keys(posVals)) {
      const base = rest[k] ?? [0, 0, 0];
      const off = f.pos?.[k] ?? [0, 0, 0];
      posVals[k][i * 3] = base[0] + off[0];
      posVals[k][i * 3 + 1] = base[1] + off[1];
      posVals[k][i * 3 + 2] = base[2] + off[2];
    }
  });
  const tracks = [
    ...bones.map((b) => new QuaternionKeyframeTrack(`${b}.quaternion`, Array.from(times), Array.from(rotVals[b]))),
    ...Object.keys(posVals).map((k) => new VectorKeyframeTrack(`${k}.position`, Array.from(times), Array.from(posVals[k]))),
  ];
  return new AnimationClip(name, duration, tracks);
}

export const TAU = Math.PI * 2;
export const sin = (p: number, off = 0): number => Math.sin(TAU * p + off);
export const cos = (p: number, off = 0): number => Math.cos(TAU * p + off);

export interface ClipSpec {
  clip: AnimationClip;
  loop: boolean;
}

/** Thin wrapper over AnimationMixer: one looping base state plus one-shots. */
export class Animator {
  readonly mixer: AnimationMixer;
  private actions = new Map<string, AnimationAction>();
  private loops = new Map<string, boolean>();
  current = '';
  private oneShot: AnimationAction | null = null;
  private oneShotEnd = 0;

  constructor(root: Object3D, clips: Record<string, ClipSpec>) {
    this.mixer = new AnimationMixer(root);
    for (const [k, spec] of Object.entries(clips)) {
      const a = this.mixer.clipAction(spec.clip);
      a.setLoop(spec.loop ? LoopRepeat : LoopOnce, spec.loop ? Infinity : 1);
      a.clampWhenFinished = !spec.loop;
      this.actions.set(k, a);
      this.loops.set(k, spec.loop);
    }
  }

  has(name: string): boolean {
    return this.actions.has(name);
  }

  /** Cross-fades the looping base state. */
  play(name: string, fade = 0.22, timeScale = 1): void {
    const next = this.actions.get(name);
    if (!next) return;
    next.timeScale = timeScale;
    if (name === this.current) return;
    const prev = this.actions.get(this.current);
    next.reset();
    next.enabled = true;
    next.setEffectiveWeight(1);
    next.play();
    if (prev && !this.oneShot) prev.crossFadeTo(next, fade, false);
    else if (prev) prev.fadeOut(fade);
    else next.fadeIn(fade);
    this.current = name;
  }

  setSpeed(timeScale: number): void {
    const a = this.actions.get(this.current);
    if (a) a.timeScale = timeScale;
  }

  /** Plays a clip once over the base state, then returns to it. */
  once(name: string, fade = 0.12, timeScale = 1): number {
    const a = this.actions.get(name);
    if (!a) return 0;
    const base = this.actions.get(this.current);
    if (this.oneShot && this.oneShot !== a) this.oneShot.fadeOut(fade);
    a.reset();
    a.timeScale = timeScale;
    a.setLoop(LoopOnce, 1);
    a.clampWhenFinished = true;
    a.enabled = true;
    a.setEffectiveWeight(1);
    a.fadeIn(fade);
    a.play();
    base?.fadeOut(fade);
    this.oneShot = a;
    const dur = a.getClip().duration / Math.max(0.01, timeScale);
    this.oneShotEnd = dur;
    return dur;
  }

  get busy(): boolean {
    return this.oneShot !== null;
  }

  update(dt: number): void {
    this.mixer.update(dt);
    if (this.oneShot) {
      this.oneShotEnd -= dt;
      if (this.oneShotEnd <= 0.12) {
        const base = this.actions.get(this.current);
        this.oneShot.fadeOut(0.15);
        if (base) {
          base.reset();
          base.enabled = true;
          base.setEffectiveWeight(1);
          base.fadeIn(0.15);
          base.play();
        }
        this.oneShot = null;
      }
    }
  }

  dispose(): void {
    this.mixer.stopAllAction();
    this.mixer.uncacheRoot(this.mixer.getRoot());
  }
}

// ---------------------------------------------------------------------------
// Skinning: rigid parts authored in bone space become one SkinnedMesh per
// material, every vertex weighted fully to its bone. One skeleton drives all
// of a model's meshes on the GPU.

export interface SkinPart {
  bone: string;
  geo: BufferGeometry;
  mat: Material;
  cast?: boolean;
}

export interface SkinnedBatch {
  geo: BufferGeometry;
  mat: Material;
  cast: boolean;
}

/** Rest-pose model-space position of every bone (rest rotations are identity). */
export function restOffsets(rest: Record<string, readonly number[]>, parents: Record<string, string | null>): Record<string, Vector3> {
  const out: Record<string, Vector3> = {};
  const resolve = (b: string): Vector3 => {
    if (out[b]) return out[b];
    const r = rest[b];
    const v = new Vector3(r[0], r[1], r[2]);
    const p = parents[b];
    if (p) v.add(resolve(p));
    out[b] = v;
    return v;
  };
  for (const b of Object.keys(rest)) resolve(b);
  return out;
}

/** Bakes parts into skinned geometry batches (cacheable across instances). */
export function bakeSkin(parts: SkinPart[], boneOrder: string[], offsets: Record<string, Vector3>): SkinnedBatch[] {
  const groups = new Map<string, { mat: Material; cast: boolean; geos: BufferGeometry[] }>();
  for (const p of parts) {
    const idx = boneOrder.indexOf(p.bone);
    const g = prep(p.geo);
    const o = offsets[p.bone];
    g.translate(o.x, o.y, o.z);
    const n = g.attributes.position.count;
    const si = new Uint16Array(n * 4);
    const sw = new Float32Array(n * 4);
    for (let i = 0; i < n; i++) {
      si[i * 4] = idx;
      sw[i * 4] = 1;
    }
    g.setAttribute('skinIndex', new BufferAttribute(si, 4));
    g.setAttribute('skinWeight', new BufferAttribute(sw, 4));
    const cast = p.cast !== false;
    const key = `${p.mat.uuid}|${cast}`;
    let grp = groups.get(key);
    if (!grp) groups.set(key, (grp = { mat: p.mat, cast, geos: [] }));
    grp.geos.push(g);
  }
  const out: SkinnedBatch[] = [];
  for (const grp of groups.values()) {
    const geo = mergeGeometries(grp.geos, false)!;
    grp.geos.forEach((g) => g.dispose());
    geo.computeBoundingSphere();
    geo.boundingSphere!.radius *= 1.6;
    out.push({ geo, mat: grp.mat, cast: grp.cast });
  }
  return out;
}

/** Creates skinned meshes for baked batches, sharing one skeleton. */
export function skinMeshes(root: Object3D, bones: Bone[], offsets: Record<string, Vector3>, batches: SkinnedBatch[]): SkinnedMesh[] {
  const inverses = bones.map((b) => new Matrix4().makeTranslation(-offsets[b.name].x, -offsets[b.name].y, -offsets[b.name].z));
  const skeleton = new Skeleton(bones, inverses);
  return batches.map((b) => {
    const m = new SkinnedMesh(b.geo, b.mat);
    m.castShadow = b.cast;
    m.receiveShadow = false;
    root.add(m);
    m.bind(skeleton, new Matrix4());
    return m;
  });
}
