// Builds a TypeScript module of game-icons.net SVG paths for one game.
//
// Usage:
//   git clone --depth 1 https://github.com/game-icons/icons /tmp/game-icons
//   node scripts/game-icons.mjs /tmp/game-icons src/games/year-zero/art/icons.manifest.json src/games/year-zero/art/icons.ts
//
// The manifest maps our icon keys to "author/icon-name" in the game-icons repo.
// Icons are CC BY 3.0 (a few CC0); credits are generated alongside the paths.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [, , repo, manifestPath, outPath] = process.argv;
if (!repo || !manifestPath || !outPath) {
  console.error('usage: node scripts/game-icons.mjs <game-icons-repo> <manifest.json> <out.ts>');
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const paths = {};
for (const source of new Set(Object.values(manifest))) {
  const svg = readFileSync(join(repo, `${source}.svg`), 'utf8');
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]).filter((d) => d !== 'M0 0h512v512H0z');
  if (!ds.length) throw new Error(`no path data in ${source}`);
  paths[source] = shrink(ds.join(' '));
}

/** Round coordinates to one decimal (invisible at icon sizes), roughly halving the size. */
function shrink(d) {
  return d.replace(/-?\d*\.\d+/g, (m, offset, str) => {
    let v = (Math.round(parseFloat(m) * 10) / 10).toString();
    if (v === '-0') v = '0';
    if (v.startsWith('0.')) v = v.slice(1);
    else if (v.startsWith('-0.')) v = `-${v.slice(2)}`;
    // Keep neighbouring numbers apart when rounding removes the separating dot.
    if (!v.includes('.') && str[offset + m.length] === '.') v += ' ';
    if (/[\d.]/.test(str[offset - 1] ?? '') && !/^[-.]/.test(v)) v = ` ${v}`;
    return v;
  });
}

const keys = Object.keys(manifest).sort();
const lines = [
  '// Generated by scripts/game-icons.mjs from https://game-icons.net — do not edit by hand.',
  '// Icons by their respective authors, licensed CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/).',
  '',
  `export type IconKey =\n${keys.map((k) => `  | '${k}'`).join('\n')};`,
  '',
  '/** Icon key -> "author/icon-name" on game-icons.net. */',
  'export const ICON_SOURCE: Record<IconKey, string> = {',
  ...keys.map((k) => `  '${k}': '${manifest[k]}',`),
  '};',
  '',
  '/** SVG path data in a 512x512 box, keyed by source. */',
  'export const ICON_PATH: Record<string, string> = {',
  ...Object.keys(paths).sort().map((s) => `  '${s}': '${paths[s]}',`),
  '};',
  '',
];
writeFileSync(outPath, lines.join('\n'));
const bytes = lines.join('\n').length;
console.log(`${keys.length} keys, ${Object.keys(paths).length} icons, ${(bytes / 1024).toFixed(1)} KB -> ${outPath}`);
